### ISSUE TITLE
Unable to install for browser using NPM

### ISSUE THREAD

**Issue by mwawrusch** [dfuse-io/client-js#1]
I get this message
```
ERROR in ./node_modules/@dfuse/client/dist/dfuse-client.umd.js
Module not found: Error: Can't resolve 'fs' in '/Users/mwawrusch/Dev/roji/roji-shop/node_modules/@dfuse/client/dist'
```
in version "@dfuse/client": "0.2.0-rc.28",
It worked in version 0.2.0-rc.01 - don't know yet where it broke in between

**Comment by maoueh** [comment]
@mwawrusch Which bundling tool are you using (if any)? (like Webpack or something).

We added a UMD build and it seems the `fs` dependency is still included in the output build file. I will look into it.

**Comment by maoueh** [comment]
I just published `0.2.0-rc.30` that should fix your issue. Please report it's indeed fixing the problem.

We provide an ESM build also that could be picked by your bundler instead of the UMD build. Doing this would enable you to use tree-shaking feature of the bundler which would remove stuff that you do not use from the library.

**Comment by mwawrusch** [comment]
Yes it works, thank you. Using angular-cli here, which I still think is built on top of webpack.

**Comment by maoueh** [comment]
Excellent!

Yeah most likely built on it, maybe an old version. Not a big deal as the library is quite small, but if you need to optimize your build output at some point, look into that, using the ESM as defined by the library  `package.json` `module` field instead of the `UMD` build.
